PRAGMA foreign_keys = ON;
PRAGMA auto_vacuum  = FULL;

CREATE TABLE SYNCPREFERENCES(LOVID VARCHAR2(50) PRIMARY KEY,LOVNAME VARCHAR2(50),LOVDESCRIPTION VARCHAR2(200),SYNCCOUNT VARCHAR2(50),LASTSYNCDATETIME VARCHAR2(100),LOVCLASSNAME VARCHAR2(50),LOVCOLLECTVAR VARCHAR2(50));
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('1','Entity','Entity Description','0','2014-12-01 14:00:00','WarehouseDC','s_warehouse');
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('2','FA Book','FA Book Description','0','2014-12-01 14:10:00','SubinventoryDC','s_subInventories');
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('3','Inventory Org','Inventory Org Description','0','2014-12-02 14:10:00','LocatorDC','s_locator');
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('4','Ledger','Ledger Description','0','2014-12-02 14:15:00','UOMDC','s_uom');
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('5','OU','OU Description','0','2014-12-02 14:16:00','CategorySetDC','s_categorySets');
INSERT INTO SYNCPREFERENCES(LOVID,LOVNAME,LOVDESCRIPTION,SYNCCOUNT,LASTSYNCDATETIME,LOVCLASSNAME,LOVCOLLECTVAR) VALUES('6','Period','Period Description','0','2014-12-02 14:17:00','CategoryCodeDC','s_categorycode');